name: main

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    main:
        runs-on: ${{ matrix.image }}
        strategy:
            matrix:
                image: [macos-10.15, ubuntu-18.04, windows-2019]
        steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
              node-version: 12.x
        - name: Get NPM cache directory
          id: npm-cache
          run: echo "::set-output name=dir::$(npm config get cache)"
        - name: NPM cache
          uses: actions/cache@v2
          with:
              path: ${{ steps.npm-cache.outputs.dir }}
              key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        - name: NPM install
          run: npm ci
        - name: NPM build
          run: npm run compile
        - name: Test
          run: npm test
